[package]
name = "chp_5_6_hw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
criterion = "0.4.0"
criterion-plot = "0.5.0"
