name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: cd chp_8_hw && cargo build --verbose
    - name: Run tests
      run: cd chp_8_hw && cargo test --verbose
